services:
  - type: web
    name: exam-questions-app
    runtime: node
    plan: free
    branch: main
    buildCommand: npx prisma generate && npx next build && cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/
    startCommand: node .next/standalone/server.js
    envVars:
      - key: DATABASE_URL
        value: file:./db/custom.db
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "20"