services:
  - type: web
    name: jee-pyq-vault
    runtime: node
    plan: free
    branch: main
    buildCommand: npx prisma generate && bun install && bun run build
    startCommand: bun run start
    healthCheckPath: /api
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        value: file:./db/custom.db
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          name: jee-pyq-vault
          type: web
          property: hostport