#!/bin/bash
# Master scraping runner - scrapes all chapters in batches
# Usage: bash scripts/run-scrape-all.sh
set -e

mkdir -p /tmp/scraped
LOG="/tmp/scrape-all.log"

echo "=== JEE PYQ Scraping Started at $(date) ===" | tee "$LOG"

# Define all chapters: exam_type subject chapter_slug "Chapter Name"
CHAPTERS=(
  # JEE Main Physics (28)
  "jee-main physics units-and-measurements 'Units & Measurements'"
  "jee-main physics vector-algebra 'Vector Algebra'"
  "jee-main physics motion-in-a-straight-line 'Motion in a Straight Line'"
  "jee-main physics motion-in-a-plane 'Motion in a Plane'"
  "jee-main physics circular-motion 'Circular Motion'"
  "jee-main physics laws-of-motion 'Laws of Motion'"
  "jee-main physics work-power-and-energy 'Work Power & Energy'"
  "jee-main physics center-of-mass 'Centre of Mass'"
  "jee-main physics rotational-motion 'Rotational Motion'"
  "jee-main physics properties-of-matter 'Properties of Matter'"
  "jee-main physics heat-and-thermodynamics 'Heat & Thermodynamics'"
  "jee-main physics simple-harmonic-motion 'Simple Harmonic Motion'"
  "jee-main physics waves 'Waves'"
  "jee-main physics gravitation 'Gravitation'"
  "jee-main physics electrostatics 'Electrostatics'"
  "jee-main physics current-electricity 'Current Electricity'"
  "jee-main physics capacitor 'Capacitor'"
  "jee-main physics magnetics 'Magnetics'"
  "jee-main physics magnetic-properties-of-matter 'Magnetic Properties'"
  "jee-main physics electromagnetic-induction 'Electromagnetic Induction'"
  "jee-main physics alternating-current 'Alternating Current'"
  "jee-main physics electromagnetic-waves 'Electromagnetic Waves'"
  "jee-main physics wave-optics 'Wave Optics'"
  "jee-main physics geometrical-optics 'Geometrical Optics'"
  "jee-main physics atoms-and-nuclei 'Atoms & Nuclei'"
  "jee-main physics dual-nature-of-radiation 'Dual Nature of Radiation'"
  "jee-main physics electronic-devices 'Electronic Devices'"
  "jee-main physics communication-systems 'Communication Systems'"

  # JEE Main Chemistry (32)
  "jee-main chemistry some-basic-concepts-of-chemistry 'Basic Concepts'"
  "jee-main chemistry structure-of-atom 'Structure of Atom'"
  "jee-main chemistry redox-reactions 'Redox Reactions'"
  "jee-main chemistry gaseous-state 'Gaseous State'"
  "jee-main chemistry chemical-equilibrium 'Chemical Equilibrium'"
  "jee-main chemistry ionic-equilibrium 'Ionic Equilibrium'"
  "jee-main chemistry solutions 'Solutions'"
  "jee-main chemistry thermodynamics 'Thermodynamics'"
  "jee-main chemistry electrochemistry 'Electrochemistry'"
  "jee-main chemistry chemical-kinetics-and-nuclear-chemistry 'Chemical Kinetics'"
  "jee-main chemistry solid-state 'Solid State'"
  "jee-main chemistry surface-chemistry 'Surface Chemistry'"
  "jee-main chemistry periodic-table-and-periodicity 'Periodic Table'"
  "jee-main chemistry chemical-bonding-and-molecular-structure 'Chemical Bonding'"
  "jee-main chemistry isolation-of-elements 'Isolation of Elements'"
  "jee-main chemistry hydrogen 'Hydrogen'"
  "jee-main chemistry s-block-elements 's-Block Elements'"
  "jee-main chemistry p-block-elements 'p-Block Elements'"
  "jee-main chemistry d-and-f-block-elements 'd & f Block Elements'"
  "jee-main chemistry coordination-compounds 'Coordination Compounds'"
  "jee-main chemistry salt-analysis 'Salt Analysis'"
  "jee-main chemistry environmental-chemistry 'Environmental Chemistry'"
  "jee-main chemistry basics-of-organic-chemistry 'Basics of Organic Chemistry'"
  "jee-main chemistry hydrocarbons 'Hydrocarbons'"
  "jee-main chemistry haloalkanes-and-haloarenes 'Haloalkanes & Haloarenes'"
  "jee-main chemistry alcohols-phenols-and-ethers 'Alcohols Phenols & Ethers'"
  "jee-main chemistry aldehydes-ketones-and-carboxylic-acids 'Aldehydes Ketones & Carboxylic Acids'"
  "jee-main chemistry compounds-containing-nitrogen 'Compounds with Nitrogen'"
  "jee-main chemistry polymers 'Polymers'"
  "jee-main chemistry biomolecules 'Biomolecules'"
  "jee-main chemistry chemistry-in-everyday-life 'Chemistry in Everyday Life'"
  "jee-main chemistry practical-organic-chemistry 'Practical Organic Chemistry'"

  # JEE Main Mathematics (32)
  "jee-main mathematics sets-and-relations 'Sets & Relations'"
  "jee-main mathematics logarithm 'Logarithm'"
  "jee-main mathematics quadratic-equation-and-inequalities 'Quadratic Equations'"
  "jee-main mathematics sequences-and-series 'Sequences & Series'"
  "jee-main mathematics mathematical-induction 'Mathematical Induction'"
  "jee-main mathematics binomial-theorem 'Binomial Theorem'"
  "jee-main mathematics matrices-and-determinants 'Matrices & Determinants'"
  "jee-main mathematics permutations-and-combinations 'Permutations & Combinations'"
  "jee-main mathematics probability 'Probability'"
  "jee-main mathematics vector-algebra 'Vector Algebra'"
  "jee-main mathematics 3d-geometry '3D Geometry'"
  "jee-main mathematics complex-numbers 'Complex Numbers'"
  "jee-main mathematics statistics 'Statistics'"
  "jee-main mathematics mathematical-reasoning 'Mathematical Reasoning'"
  "jee-main mathematics trigonometric-ratio-and-identites 'Trigonometric Ratios'"
  "jee-main mathematics trigonometric-functions-and-equations 'Trig Functions & Equations'"
  "jee-main mathematics inverse-trigonometric-functions 'Inverse Trig Functions'"
  "jee-main mathematics properties-of-triangle 'Properties of Triangle'"
  "jee-main mathematics height-and-distance 'Height & Distance'"
  "jee-main mathematics straight-lines-and-pair-of-straight-lines 'Straight Lines'"
  "jee-main mathematics circle 'Circle'"
  "jee-main mathematics parabola 'Parabola'"
  "jee-main mathematics ellipse 'Ellipse'"
  "jee-main mathematics hyperbola 'Hyperbola'"
  "jee-main mathematics functions 'Functions'"
  "jee-main mathematics limits-continuity-and-differentiability 'Limits & Continuity'"
  "jee-main mathematics differentiation 'Differentiation'"
  "jee-main mathematics application-of-derivatives 'Application of Derivatives'"
  "jee-main mathematics indefinite-integrals 'Indefinite Integrals'"
  "jee-main mathematics definite-integration 'Definite Integration'"
  "jee-main mathematics area-under-the-curves 'Area Under Curves'"
  "jee-main mathematics differential-equations 'Differential Equations'"

  # JEE Advanced Physics (24)
  "jee-advanced physics units-and-measurements 'Units & Measurements'"
  "jee-advanced physics motion 'Motion'"
  "jee-advanced physics laws-of-motion 'Laws of Motion'"
  "jee-advanced physics work-power-and-energy 'Work Power & Energy'"
  "jee-advanced physics impulse-and-momentum 'Impulse & Momentum'"
  "jee-advanced physics rotational-motion 'Rotational Motion'"
  "jee-advanced physics properties-of-matter 'Properties of Matter'"
  "jee-advanced physics heat-and-thermodynamics 'Heat & Thermodynamics'"
  "jee-advanced physics simple-harmonic-motion 'Simple Harmonic Motion'"
  "jee-advanced physics waves 'Waves'"
  "jee-advanced physics gravitation 'Gravitation'"
  "jee-advanced physics motion-in-a-plane 'Motion in a Plane'"
  "jee-advanced physics electrostatics 'Electrostatics'"
  "jee-advanced physics current-electricity 'Current Electricity'"
  "jee-advanced physics capacitor 'Capacitor'"
  "jee-advanced physics magnetism 'Magnetism'"
  "jee-advanced physics electromagnetic-induction 'EMI'"
  "jee-advanced physics alternating-current 'Alternating Current'"
  "jee-advanced physics electromagnetic-waves 'EM Waves'"
  "jee-advanced physics geometrical-optics 'Geometrical Optics'"
  "jee-advanced physics wave-optics 'Wave Optics'"
  "jee-advanced physics practical-physics 'Practical Physics'"
  "jee-advanced physics atoms-and-nuclei 'Atoms & Nuclei'"
  "jee-advanced physics dual-nature-of-radiation 'Dual Nature'"

  # JEE Advanced Chemistry (32) - same slugs as main
  "jee-advanced chemistry some-basic-concepts-of-chemistry 'Basic Concepts'"
  "jee-advanced chemistry structure-of-atom 'Structure of Atom'"
  "jee-advanced chemistry redox-reactions 'Redox Reactions'"
  "jee-advanced chemistry gaseous-state 'Gaseous State'"
  "jee-advanced chemistry chemical-equilibrium 'Chemical Equilibrium'"
  "jee-advanced chemistry ionic-equilibrium 'Ionic Equilibrium'"
  "jee-advanced chemistry solutions 'Solutions'"
  "jee-advanced chemistry thermodynamics 'Thermodynamics'"
  "jee-advanced chemistry chemical-kinetics-and-nuclear-chemistry 'Chemical Kinetics'"
  "jee-advanced chemistry electrochemistry 'Electrochemistry'"
  "jee-advanced chemistry solid-state 'Solid State'"
  "jee-advanced chemistry surface-chemistry 'Surface Chemistry'"
  "jee-advanced chemistry periodic-table-and-periodicity 'Periodic Table'"
  "jee-advanced chemistry chemical-bonding-and-molecular-structure 'Chemical Bonding'"
  "jee-advanced chemistry isolation-of-elements 'Isolation of Elements'"
  "jee-advanced chemistry hydrogen 'Hydrogen'"
  "jee-advanced chemistry s-block-elements 's-Block Elements'"
  "jee-advanced chemistry p-block-elements 'p-Block Elements'"
  "jee-advanced chemistry d-and-f-block-elements 'd & f Block Elements'"
  "jee-advanced chemistry coordination-compounds 'Coordination Compounds'"
  "jee-advanced chemistry salt-analysis 'Salt Analysis'"
  "jee-advanced chemistry environmental-chemistry 'Environmental Chemistry'"
  "jee-advanced chemistry basics-of-organic-chemistry 'Basics of Organic Chemistry'"
  "jee-advanced chemistry hydrocarbons 'Hydrocarbons'"
  "jee-advanced chemistry haloalkanes-and-haloarenes 'Haloalkanes & Haloarenes'"
  "jee-advanced chemistry alcohols-phenols-and-ethers 'Alcohols Phenols & Ethers'"
  "jee-advanced chemistry aldehydes-ketones-and-carboxylic-acids 'Aldehydes Ketones & Carboxylic Acids'"
  "jee-advanced chemistry compounds-containing-nitrogen 'Compounds with Nitrogen'"
  "jee-advanced chemistry polymers 'Polymers'"
  "jee-advanced chemistry biomolecules 'Biomolecules'"
  "jee-advanced chemistry chemistry-in-everyday-life 'Chemistry in Everyday Life'"
  "jee-advanced chemistry practical-organic-chemistry 'Practical Organic Chemistry'"

  # JEE Advanced Mathematics (26)
  "jee-advanced mathematics quadratic-equation-and-inequalities 'Quadratic Equations'"
  "jee-advanced mathematics sequences-and-series 'Sequences & Series'"
  "jee-advanced mathematics mathematical-induction-and-binomial-theorem 'Induction & Binomial'"
  "jee-advanced mathematics matrices-and-determinants 'Matrices & Determinants'"
  "jee-advanced mathematics permutations-and-combinations 'Permutations & Combinations'"
  "jee-advanced mathematics probability 'Probability'"
  "jee-advanced mathematics vector-algebra 'Vector Algebra'"
  "jee-advanced mathematics 3d-geometry '3D Geometry'"
  "jee-advanced mathematics statistics 'Statistics'"
  "jee-advanced mathematics complex-numbers 'Complex Numbers'"
  "jee-advanced mathematics trigonometric-functions-and-equations 'Trig Functions & Equations'"
  "jee-advanced mathematics inverse-trigonometric-functions 'Inverse Trig Functions'"
  "jee-advanced mathematics properties-of-triangle 'Properties of Triangle'"
  "jee-advanced mathematics straight-lines-and-pair-of-straight-lines 'Straight Lines'"
  "jee-advanced mathematics circle 'Circle'"
  "jee-advanced mathematics parabola 'Parabola'"
  "jee-advanced mathematics ellipse 'Ellipse'"
  "jee-advanced mathematics hyperbola 'Hyperbola'"
  "jee-advanced mathematics functions 'Functions'"
  "jee-advanced mathematics limits-continuity-and-differentiability 'Limits & Continuity'"
  "jee-advanced mathematics differentiation 'Differentiation'"
  "jee-advanced mathematics application-of-derivatives 'Application of Derivatives'"
  "jee-advanced mathematics indefinite-integrals 'Indefinite Integrals'"
  "jee-advanced mathematics definite-integration 'Definite Integration'"
  "jee-advanced mathematics application-of-integration 'Application of Integration'"
  "jee-advanced mathematics differential-equations 'Differential Equations'"
)

TOTAL=${#CHAPTERS[@]}
DONE=0
ERRORS=0
SKIP=0

# Resume from START index if provided
START=${1:-0}
echo "Starting from index $START of $TOTAL chapters" | tee -a "$LOG"

for ((i=START; i<TOTAL; i++)); do
  ENTRY="${CHAPTERS[$i]}"
  # Parse: eval the entry as a command with args
  read -r EXAM SUBJECT SLUG NAME <<< "$ENTRY"
  
  DONE=$((DONE + 1))
  echo "" | tee -a "$LOG"
  echo "[$DONE/$TOTAL] ($(( (DONE * 100) / TOTAL ))%) $EXAM/$SUBJECT/$SLUG" | tee -a "$LOG"
  
  if bash /home/z/my-project/scripts/scrape-one.sh "$EXAM" "$SUBJECT" "$SLUG" /tmp/scraped "$NAME" 2>&1 | tee -a "$LOG"; then
    echo "  ✓ Done" | tee -a "$LOG"
  else
    ERRORS=$((ERRORS + 1))
    echo "  ✗ Error on $SLUG" | tee -a "$LOG"
  fi
  
  sleep 1
done

echo "" | tee -a "$LOG"
echo "=== Scraping Complete at $(date) ===" | tee -a "$LOG"
echo "Processed: $DONE, Errors: $ERRORS" | tee -a "$LOG"
echo "Files in /tmp/scraped: $(ls /tmp/scraped/*.json 2>/dev/null | wc -l)" | tee -a "$LOG"